/* confdefs.h */
#define PACKAGE_NAME "iperf"
#define PACKAGE_TARNAME "iperf"
#define PACKAGE_VERSION "3.13"
#define PACKAGE_STRING "iperf 3.13"
#define PACKAGE_BUGREPORT "https://github.com/esnet/iperf"
#define PACKAGE_URL "https://software.es.net/iperf/"
#define PACKAGE "iperf"
#define VERSION "3.13"
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
