/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fraunhofer_fokus_OpenMobileNetworkToolkit_iperf3Worker */

#ifndef _Included_de_fraunhofer_fokus_OpenMobileNetworkToolkit_iperf3Worker
#define _Included_de_fraunhofer_fokus_OpenMobileNetworkToolkit_iperf3Worker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fraunhofer_fokus_OpenMobileNetworkToolkit_iperf3Worker
 * Method:    iperf3Wrapper
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Iperf3Worker_iperf3Wrapper
  (JNIEnv *, jobject, jobjectArray, jstring);

JNIEXPORT jint JNICALL Java_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Iperf3Worker_iperf3Stop
  (JNIEnv *, jobject);
#ifdef __cplusplus
    }
}
#endif
#endif
