name: test
on: [push, pull_request]
jobs:
  cppcheck-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get -y update && sudo apt-get install -y cppcheck && \
        cppcheck . --force --inline-suppr
  build-test-ubuntu-ish:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get -y update && sudo apt-get install -y build-essential
    - name: build
      run: |
        ./configure && make && make check
        timeout 300 src/iperf3 -s &
        ./test_commands.sh localhost
  build-test-macos-ish:
    strategy:
      matrix:
        os: [macos-15, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        brew install coreutils
    - name: build
      run: |
        ./configure && make && make check
        gtimeout 300 src/iperf3 -s &
        ./test_commands.sh localhost
